@url = http://localhost:4902

### ADD SINGLE BOOK
POST {{url}}/books
content-type: application/json
	
{
	"title": "Book 006",
	"authors": [
		"John Granger",
		"Jines Hooplaton"
	],
	"pages": 812,
	"available": true
}

### GET ALL BOOKS
GET {{url}}/books
	
### DELETE ALL BOOKS
DELETE {{url}}/books

### GET SINGLE BOOK
GET {{url}}/books/65c041844c41360d85e13774
	
### DELETE SINGLE BOOK
DELETE {{url}}/books/65c041844c41360d85e13774

### PATCH SINGLE BOOK
PATCH {{url}}/books/65c041804c41360d85e13772
content-type: application/json
	
{
	"pages": 999
}


### GET USERS
GET {{url}}/users
	
### ADD A USER 
POST {{url}}/users
content-type: application/json
	
{
	"firstName": "Tom",
	"lastName": "Morgan",
	"mobile": 30151923190,
	"email": "tom.morgan@htl.com",
	"address" : {
		"street": "Holework Street",
		"city": "Birmingham",
		"zipCode": 31239,
		"state": "Northingham"
	}
}
